services:

  app:
    build:
      context: .
    container_name: app
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src:/app/src

  postgres:
    image: postgres:13.6
    container_name: postgres
    restart: always
    user: postgres
    volumes:
     - db-data:/var/lib/postgresql/data
    environment:
     - POSTGRES_DB=mfkn
     - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
     test: [ "CMD", "pg_isready" ]
     interval: 10s
     timeout: 5s
     retries: 5

volumes:
  db-data:
